# Generated by Django 3.1 on 2021-09-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210831_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id']},
        ),
    ]
